openapi: 3.0.3
info:
  title: Sample Ktor Backend API
  description: |
    A comprehensive Ktor backend sample with Event-Driven and Domain-Driven Design.
    
    ## API Versioning
    This API supports versioning through multiple strategies:
    - **Header-based**: Use `API-Version: 1.0` header (recommended)
    - **Path-based**: Use `/api/v1/` in URL path
    
    ## Breaking Changes Policy
    - Major version changes (1.0 → 2.0) may include breaking changes
    - Minor version changes (1.0 → 1.1) are backwards compatible
    
    ## Contract Validation
    All requests and responses are validated against this OpenAPI specification.
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com
    url: https://docs.example.com/api
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api-staging.example.com
    description: Staging server

# Global security schemes
security:
  - ApiKeyAuth: []

# Request/Response validation headers
x-validation-enabled: true

paths:
  # Health and system endpoints
  /health:
    get:
      summary: Health check endpoint
      description: Returns the current health status of the API and its dependencies
      operationId: healthCheck
      tags:
        - System
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
        '503':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'

  # User management endpoints
  /api/v1/users:
    get:
      summary: List all users
      description: Returns a paginated list of users with optional filtering
      operationId: listUsers
      tags:
        - Users
      parameters:
        - name: page
          in: query
          description: Page number (0-based)
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: size
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersListResponse'

    post:
      summary: Create a new user
      description: Creates a new user with the provided information
      operationId: createUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'

  /api/v1/users/{id}:
    get:
      summary: Get user by ID
      description: Returns a single user by their ID
      operationId: getUserById
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: User ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Update user
      description: Updates an existing user with new information
      operationId: updateUser
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: User ID
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication

  schemas:
    # User schemas
    CreateUserRequest:
      type: object
      required:
        - email
        - firstName
        - lastName
      properties:
        email:
          type: string
          format: email
          description: User's email address
          example: "john.doe@example.com"
        firstName:
          type: string
          minLength: 1
          maxLength: 50
          description: User's first name
          example: "John"
        lastName:
          type: string
          minLength: 1
          maxLength: 50
          description: User's last name
          example: "Doe"

    UpdateUserRequest:
      type: object
      properties:
        firstName:
          type: string
          minLength: 1
          maxLength: 50
          description: User's first name
          example: "John"
        lastName:
          type: string
          minLength: 1
          maxLength: 50
          description: User's last name
          example: "Doe"

    UserResponse:
      type: object
      required:
        - id
        - email
        - firstName
        - lastName
        - status
        - createdAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique user identifier
          example: "123e4567-e89b-12d3-a456-426614174000"
        email:
          type: string
          format: email
          description: User's email address
          example: "john.doe@example.com"
        firstName:
          type: string
          description: User's first name
          example: "John"
        lastName:
          type: string
          description: User's last name
          example: "Doe"
        status:
          $ref: '#/components/schemas/UserStatus'
        createdAt:
          type: string
          format: date-time
          description: User creation timestamp
          example: "2023-12-01T10:30:00Z"

    UserStatus:
      type: string
      enum:
        - ACTIVE
        - INACTIVE
        - SUSPENDED
      description: User account status

    UsersListResponse:
      type: object
      required:
        - users
        - totalCount
        - page
        - size
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/UserResponse'
        totalCount:
          type: integer
          description: Total number of users
          example: 150
        page:
          type: integer
          description: Current page number (0-based)
          example: 0
        size:
          type: integer
          description: Number of items per page
          example: 20

    # System schemas
    HealthCheck:
      type: object
      required:
        - status
        - timestamp
        - checks
      properties:
        status:
          type: string
          enum:
            - UP
            - DOWN
            - DEGRADED
          description: Overall service health status
        timestamp:
          type: string
          format: date-time
          description: Health check timestamp
        checks:
          type: array
          items:
            $ref: '#/components/schemas/HealthResponseChecks'

    HealthResponseChecks:
      type: object
      required:
        - name
        - status
      properties:
        name:
          type: string
          description: Name of the health check
        status:
          type: string
          enum:
            - UP
            - DOWN
          description: Status of this specific check
        details:
          type: object
          description: Additional details about the check

    # Error schemas
    ErrorResponse:
      type: object
      required:
        - error
        - message
        - timestamp
      properties:
        error:
          type: string
          description: Error code or type
          example: "USER_NOT_FOUND"
        message:
          type: string
          description: Human-readable error message
          example: "User with ID 123 was not found"
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
          example: "2023-12-01T10:30:00Z"

    ValidationErrorResponse:
      type: object
      required:
        - error
        - message
        - timestamp
        - validationErrors
      properties:
        error:
          type: string
          description: Error code
          example: "VALIDATION_FAILED"
        message:
          type: string
          description: General error message
          example: "Request validation failed"
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
        validationErrors:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'

    ValidationError:
      type: object
      required:
        - field
        - message
      properties:
        field:
          type: string
          description: Field that failed validation
          example: "email"
        message:
          type: string
          description: Validation error message
          example: "Email format is invalid"
        rejectedValue:
          description: The value that was rejected
          example: "invalid-email"
